name: "Lint Dockerfile"

on:
  pull_request:
    paths:
      - "**/Dockerfile.*"
      - "**/docker-compose.*"
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  hadolint:
    name: "Lint Docker with hadolint"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: false
          level: warning
          filter_mode: nofilter
